### ISSUE TITLE
Mailing list "ee4j-community" shows as invalid

### ISSUE THREAD

**Issue by thesurenk** [eclipse-ee4j/ee4j-website#30]
On this page https://projects.eclipse.org/projects/ee4j/contact , selecting "ee4j-community" under "Project Mailing Lists" shows "This is not a valid mailing list".

<img width="686" alt="screen shot 2018-06-15 at 4 17 14 pm" src="https://user-images.githubusercontent.com/902972/41489992-9c3b1038-70b7-11e8-9dfb-d2872ee9d352.png">

**Comment by m0mus** [comment]
It's been renamed to jakarta.ee-community@eclipse.org. Web site is fixed.
